services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        value: base64:BwPHc/hKMfUbiWU1Qbxymfkd0vBr2vtOq38euTa5sGE=
      - key: DATABASE_URL
        value: postgresql://postgres:rhyiotahari123@db.sljbkhdssflyyienixka.supabase.co:5432/postgres
      - key: DB_CONNECTION
        value: pgsql
