services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true" # Set to "false" after debugging
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        value: base64:BwPHc/hKMfUbiWU1Qbxymfkd0vBr2vtOq38euTa5sGE=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.sljbkhdssflyyienixka
      - key: DB_PASSWORD
        value: i2Wrjj5JMm3SiMTz
      - key: DATABASE_URL # Keep DATABASE_URL for compatibility
        value: postgresql://postgres.sljbkhdssflyyienixka:i2Wrjj5JMm3SiMTz@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
